### ISSUE TITLE
How do i start the server 

### ISSUE THREAD

**Issue by pilotkid2012** [angelozerr/CodeMirror-Java#1]
Hi i have imported the file into eclipse and everything with "package codemirror;" Will not run and anything with the package code mirror e.g. (package codemirror.executor.xquery.saxon;) how can I start and run the server? I cant seem to get it to work
![screen shot 2013-09-08 at 11 09 30 am](https://f.cloud.github.com/assets/5377634/1103445/7d5e99a2-18a9-11e3-903e-4f195f6c5c33.png)
 Thank you -- carbonbased lifeform 125006080

**Comment by angelozerr** [comment]
You must use maven to import this project (I use M2Eclipse for that). Note that this project is just to shows demo for https://github.com/angelozerr/CodeMirror-XQuery

**Comment by pilotkid2012** [comment]
Ok but it will run right?

**Comment by angelozerr** [comment]
Yes it run right. You must import the project with M2Eclipse. If you do that, M2Eclipse will create a clean Eclipse Project with clean classpath (it will download CXF dependencies and update your classpath with those dependencies).
